### ISSUE TITLE
Desabilitar rotina de execução de spiders fora do ambiente

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#823]
Ao criar um fork deste repositório, as Actions do GitHub são copiadas junto. Todos os dias, as pessoas que tem seu fork atualizado com a main recebe mensagens de falha de execução da raspagem. 

![image](https://user-images.githubusercontent.com/44185775/218495881-373725c9-fa9f-45b1-9746-bf65ae7c898f.png)

Ainda que seja um problema contornável através da desabilitação das Actions no fork, seria interessante se não disparasse. Uma solução possível é se caso não detecte as variáveis de ambiente necessárias a ação não deveria executar

**Comment by AlexJBSilva** [comment]
Os forks desse repositório 'base' "nascem" com as actions desabilitadas (imagem abaixo).

Mas não é incomum pessoas desenvolvedoras habilitarem as actions em seu próprio fork para algum uso específico (com uma nova action).
![ActionsDisabled](https://github.com/okfn-brasil/querido-diario/assets/104526833/389fe048-07f0-45a5-a4c5-9a2f878c13d0)

Uma alternativa para reduzir o impacto é: só prosseguir com a execução da action caso ela tenha sido iniciada de organização/repositório especificados em uma condição de controle.

```yaml
name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
```

Referência: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
